# Generated by Django 4.1.6 on 2023-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
