# Generated by Django 4.1.6 on 2023-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_city_house_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
