# Generated by Django 4.1.6 on 2023-04-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_names',
            field=models.TextField(default='No guest names provided'),
        ),
    ]
